# Set a base URL variable
@baseUrl = http://localhost:3001


### get the home endpoint
GET {{baseUrl}}/api
###



### ---------- for categories ----------

### create a category
POST {{baseUrl}}/api/category/create
Content-Type: application/json

{
    "name": "Electrics"
}
###


### delete a category
DELETE {{baseUrl}}/api/category/delete/Electricals
###


### get all categories
GET {{baseUrl}}/api/category/getAll
###


### update a category name
PUT {{baseUrl}}/api/category/update/Electrics/Electricals
###